/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twoparty_mpc_NativeMpc */

#ifndef _Included_twoparty_mpc_NativeMpc
#define _Included_twoparty_mpc_NativeMpc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     twoparty_mpc_NativeMpc
 * Method:    ecdsaKeygen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_twoparty_mpc_NativeMpc_ecdsaKeygen
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
